apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: aplicacoes-prod
  namespace: argo
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/bernardolsp/aula-bonde-rs.git
      revision: HEAD
      directories:
      - path: ambiente-de-prod/*
  template:
    metadata:
      name: '{{index .path.segments 1}}-prod'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/bernardolsp/aula-bonde-rs.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 1}}-prod'
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true